spring:
  datasource:
    url: jdbc:mysql://family-db.clb1xa1lzrvw.us-east-1.rds.amazonaws.com:3306/family-db?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: mirim123
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
  profiles:
    active: local
  jpa:
    database: mysql
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true